In [1]:
!python -m pip install pandas corus nltk scikit-learn seaborn matplotlib

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting corus
  Downloading corus-0.10.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading corus-0.10.0-py3-none-any.whl (83 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.7/83.7 kB 4.1 MB/s eta 0:00:00
Installing collected packages: corus
Successfully installed corus-0.10.0

Были проблемы с библиотеками которые завязаны на curos, поэтому просто через curl скачиваем

In [2]:
!curl -L -O https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  502M  100  502M    0     0   102M      0  0:00:04  0:00:04 --:--:--  123M

In [3]:
!pip install nltk
import nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [4]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [5]:
import re
import os
import urllib.request

import matplotlib.pyplot as plt
import nltk
import pandas as pd
import seaborn as sns
import numpy as np
from corus import load_lenta

from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer

from sklearn.dummy import DummyClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.pipeline import Pipeline

In [6]:
import random

# Фиксируем воспроизводимость результатов

In [7]:
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)

In [8]:
base_dir = 'lenta-ru-news.csv.gz'
records = load_lenta(base_dir)

data =[]

# берем топики нужные
for record in records:
    data.append({
        'title': record.title,
        'text': record.text,
        'topic': record.topic
    })

df = pd.DataFrame(data)

In [9]:
df.head()

,title,text,topic
0,Названы регионы России с самой высокой смертно...,Вице-премьер по социальным вопросам Татьяна Го...,Россия
1,Австрия не представила доказательств вины росс...,Австрийские правоохранительные органы не предс...,Спорт
2,Обнаружено самое счастливое место на планете,Сотрудники социальной сети Instagram проанализ...,Путешествия
3,В США раскрыли сумму расходов на расследование...,С начала расследования российского вмешательст...,Мир
4,Хакеры рассказали о планах Великобритании зами...,Хакерская группировка Anonymous опубликовала н...,Мир

In [10]:
!pip install pymorphy3
import pymorphy3

Collecting pymorphy3
  Downloading pymorphy3-2.0.6-py3-none-any.whl.metadata (2.4 kB)
Collecting dawg2-python>=0.8.0 (from pymorphy3)
  Downloading dawg2_python-0.9.0-py3-none-any.whl.metadata (7.5 kB)
Collecting pymorphy3-dicts-ru (from pymorphy3)
  Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: setuptools>=68.2.2 in /usr/local/lib/python3.12/dist-packages (from pymorphy3) (75.2.0)
Downloading pymorphy3-2.0.6-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.9/53.9 kB 2.2 MB/s eta 0:00:00
Downloading dawg2_python-0.9.0-py3-none-any.whl (9.3 kB)
Downloading pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 63.4 MB/s eta 0:00:00
Installing collected packages: pymorphy3-dicts-ru, dawg2-python, pymorphy3
Successfully installed dawg2-python-0.9.0 pymorphy3-2.0.6 pymorphy3-dicts-ru-2.4.417150.4580142

In [11]:
from pymorphy3 import MorphAnalyzer

In [12]:
ru_stopwords = set(stopwords.words('russian'))

In [13]:
stemmer = SnowballStemmer(language='russian')

In [14]:
morph = MorphAnalyzer()

re_url = re.compile(r'http\S+|www\S+')
re_non_alpha = re.compile(r'[^а-яА-ЯёЁ\s]')

def preprocess_text(text):

    if not isinstance(text, str):
        return ""
    text = text.lower()

    text = re_url.sub('', text)

    text = re_non_alpha.sub(' ', text)

    tokens = []
    for word in text.split():
        if word and word not in ru_stopwords:
            # Стемминг слова, пробовал лемматизацию но там не дождался обработки
            stem = stemmer.stem(word)
            tokens.append(stem)

    return ' '.join(tokens)

In [15]:
# Объединим заголовок и текст для получения более полного контекста

df['content'] = df['title'].fillna('') + ' ' + df['text'].fillna('')

In [16]:
df.head()

,title,text,topic,content
0,Названы регионы России с самой высокой смертно...,Вице-премьер по социальным вопросам Татьяна Го...,Россия,Названы регионы России с самой высокой смертно...
1,Австрия не представила доказательств вины росс...,Австрийские правоохранительные органы не предс...,Спорт,Австрия не представила доказательств вины росс...
2,Обнаружено самое счастливое место на планете,Сотрудники социальной сети Instagram проанализ...,Путешествия,Обнаружено самое счастливое место на планете С...
3,В США раскрыли сумму расходов на расследование...,С начала расследования российского вмешательст...,Мир,В США раскрыли сумму расходов на расследование...
4,Хакеры рассказали о планах Великобритании зами...,Хакерская группировка Anonymous опубликовала н...,Мир,Хакеры рассказали о планах Великобритании зами...

In [20]:
df_clean, t = train_test_split(
    df,
    train_size=100000,
    random_state=RANDOM_STATE,
    stratify=df['topic']

)

df_clean = df_clean.reset_index(drop=True)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

окей чета какая то ошибка, исправляем ниже

In [17]:
counts = df['topic'].value_counts()
valid_topics = counts[counts >= 50].index

df_clean = df[df['topic'].isin(valid_topics)]

In [18]:
df_final, t = train_test_split(
    df_clean,
    train_size=100000,
    random_state=RANDOM_STATE,
    stratify=df_clean['topic']

)

df_final = df_final.reset_index(drop=True)

In [19]:
df_final.head()

,title,text,topic,content
0,Государственный департамент США не устраивают ...,"Государственный департамент США заявил, что за...",Мир,Государственный департамент США не устраивают ...
1,Южная Осетия будет просить Россию отменить эко...,Власти Южной Осетии намерены просить Москву от...,Бывший СССР,Южная Осетия будет просить Россию отменить эко...
2,На выходных в Москве прошла пушкинская Велоночь,С 27 на 28 сентября состоялась Восьмая Московс...,Дом,На выходных в Москве прошла пушкинская Велоноч...
3,В Лондоне при взрыве пострадал рабочий,"В центре Лондона 7 февраля произошел взрыв, со...",Мир,В Лондоне при взрыве пострадал рабочий В центр...
4,Польша начнет массовый снос советских памятников,Власти Польши планируют снести почти 30 памятн...,Мир,Польша начнет массовый снос советских памятник...

In [20]:
df_final['cleaned_text'] = df_final['content'].apply(preprocess_text)

In [21]:
X = df_final['cleaned_text']
y = df_final['topic']

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.4,
    random_state=RANDOM_STATE,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    random_state=RANDOM_STATE,
    stratify=y_temp
)

In [22]:
X

0        государствен департамент сша устраива бумажн п...
1        южн осет прос росс отмен экономическ санкц вла...
2        выходн москв прошл пушкинск велоноч сентябр со...
3        лондон взрыв пострада рабоч центр лондон февра...
4        польш начнет массов снос советск памятник влас...
                               ...
99995    кгб белорусс обвин джозеф ке коммерческ шпиона...
99996    летн бабушк казахста покор интернет рэп житух ...
99997    медвед подготов закон увольнен связ утрат дове...
99998    собак науч наход детск порнограф запах правоох...
99999    испачка рвот американск журналистк невозмутим ...
Name: cleaned_text, Length: 100000, dtype: object

In [23]:
y

0                   Мир
1           Бывший СССР
2                   Дом
3                   Мир
4                   Мир
              ...
99995       Бывший СССР
99996    Интернет и СМИ
99997            Россия
99998    Интернет и СМИ
99999    Интернет и СМИ
Name: topic, Length: 100000, dtype: object

# Dummy

In [24]:
dummy = DummyClassifier(strategy="stratified", random_state=RANDOM_STATE)
dummy.fit(X_train, y_train)

y_pred_dummy = dummy.predict(X_val)
print("бейзлайн\n", classification_report(y_val, y_pred_dummy, zero_division=0))

бейзлайн
                    precision    recall  f1-score   support

                        0.00      0.00      0.00         6
   69-я параллель       0.00      0.00      0.00        35
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.00      0.01      0.00       200
      Бывший СССР       0.07      0.07      0.07      1444
              Дом       0.03      0.03      0.03       588
         Из жизни       0.02      0.02      0.02       747
   Интернет и СМИ       0.06      0.06      0.06      1208
             Крым       0.00      0.00      0.00        18
    Культпросвет        0.00      0.00      0.00         9
         Культура       0.07      0.08      0.08      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.18      0.18      0.18      3698
  Наука и техника       0.08      0.09      0.08      1437
      Путешествия       0.02      0.02      0.02       174
           Россия       0.22      0.22      0.22      4342
Силовые структуры       0.03      0.03      0.03       530
            Спорт       0.08      0.08      0.08      1742
         Ценности       0.01      0.01      0.01       210
        Экономика       0.10      0.10      0.10      2151

         accuracy                           0.12     20000
        macro avg       0.05      0.05      0.05     20000
     weighted avg       0.12      0.12      0.12     20000

# CountVectorizer

In [25]:
CV = Pipeline([
    ('vect', CountVectorizer()),
    ('clf', LogisticRegression(class_weight='balanced', random_state=RANDOM_STATE, max_iter= 500))
])

CV.fit(X_train, y_train)
y_pred_cv = CV.predict(X_val)
print("Countvector \n", classification_report(y_val, y_pred_cv, zero_division=0))

Countvector
                    precision    recall  f1-score   support

                        0.00      0.00      0.00         6
   69-я параллель       0.60      0.43      0.50        35
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.49      0.51      0.50       200
      Бывший СССР       0.81      0.82      0.81      1444
              Дом       0.81      0.84      0.82       588
         Из жизни       0.57      0.62      0.59       747
   Интернет и СМИ       0.72      0.70      0.71      1208
             Крым       0.33      0.28      0.30        18
    Культпросвет        0.20      0.22      0.21         9
         Культура       0.87      0.87      0.87      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.80      0.79      0.79      3698
  Наука и техника       0.79      0.81      0.80      1437
      Путешествия       0.69      0.68      0.69       174
           Россия       0.79      0.78      0.78      4342
Силовые структуры       0.56      0.56      0.56       530
            Спорт       0.96      0.96      0.96      1742
         Ценности       0.84      0.81      0.83       210
        Экономика       0.82      0.82      0.82      2151

         accuracy                           0.79     20000
        macro avg       0.58      0.58      0.58     20000
     weighted avg       0.79      0.79      0.79     20000

# TfidfVectorizer

In [26]:
TD_CV = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', LogisticRegression(class_weight='balanced', random_state=RANDOM_STATE, max_iter=1000))
])

TD_CV.fit(X_train, y_train)
y_pred_td_cv = TD_CV.predict(X_val)
print("tfidf\n", classification_report(y_val, y_pred_td_cv, zero_division=0))

tfidf
                    precision    recall  f1-score   support

                        0.00      0.00      0.00         6
   69-я параллель       0.57      0.60      0.58        35
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.35      0.69      0.47       200
      Бывший СССР       0.78      0.86      0.82      1444
              Дом       0.74      0.88      0.80       588
         Из жизни       0.49      0.76      0.59       747
   Интернет и СМИ       0.74      0.73      0.74      1208
             Крым       0.15      0.44      0.23        18
    Культпросвет        0.19      0.33      0.24         9
         Культура       0.86      0.88      0.87      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.84      0.76      0.80      3698
  Наука и техника       0.80      0.81      0.81      1437
      Путешествия       0.50      0.79      0.61       174
           Россия       0.86      0.70      0.77      4342
Силовые структуры       0.44      0.69      0.54       530
            Спорт       0.96      0.96      0.96      1742
         Ценности       0.80      0.84      0.82       210
        Экономика       0.85      0.79      0.82      2151

         accuracy                           0.79     20000
        macro avg       0.55      0.63      0.57     20000
     weighted avg       0.81      0.79      0.79     20000

# tfidf показал себя буквально чуть чуть лучше чем CV

# сделаем тюнинг параметров

пытался сделать такой перебор:

param_grid = {
    # диапазон n-грамм
    'vect__ngram_range': [(1, 1), (1, 2), (1, 3)],
    
    # Минимальная частота слова
    'vect__min_df': [5, 10, 20],
    
    # Максимальная частота слова
    'vect__max_df': [0.7, 0.8, 0.9],
    
    # Использование sublinear_tf
    'vect__sublinear_tf': [True],
    
    # Параметр регуляризации C
    'clf__C': [0.01, 0.1, 1.0, 10.0],
    
    # Тип регуляризации, можно попробовать l1,но использую l2
    'clf__penalty': ['l2']
}

но уже жду 32 минуты. сократил перебор

не успел параметры перебрать... все равно

In [31]:

param_grid = {
    'vect__ngram_range': [(1, 1), (1, 2)],
    'vect__min_df': [20, 40],
    'vect__max_df': [0.6, 0.8],
    'vect__sublinear_tf': [True],
    'clf__C': [0.1, 1, 10]
}

grid = GridSearchCV(
    estimator=TD_CV,
    param_grid=param_grid,
    cv=3,
    scoring='f1_weighted',
    n_jobs=3,
    verbose=2
)

grid.fit(X_train, y_train)

print("best params", grid.best_params_)
print("Лучший score", grid.best_score_)
best_model = grid.best_estimator_

Fitting 3 folds for each of 24 candidates, totalling 72 fits
best params {'clf__C': 10, 'vect__max_df': 0.8, 'vect__min_df': 20, 'vect__ngram_range': (1, 2), 'vect__sublinear_tf': True}
Лучший score 0.8135387416222665

In [33]:
y_pred = best_model.predict(X_test)
print("finality \n", classification_report(y_test, y_pred, zero_division=0))

finality
                    precision    recall  f1-score   support

                        1.00      0.20      0.33         5
   69-я параллель       0.84      0.62      0.71        34
       Библиотека       0.00      0.00      0.00         2
           Бизнес       0.54      0.54      0.54       200
      Бывший СССР       0.81      0.87      0.84      1445
              Дом       0.80      0.85      0.83       588
         Из жизни       0.61      0.69      0.65       747
   Интернет и СМИ       0.74      0.76      0.75      1209
             Крым       0.45      0.50      0.47        18
    Культпросвет        0.20      0.22      0.21         9
         Культура       0.86      0.88      0.87      1455
          Легпром       0.00      0.00      0.00         3
              Мир       0.83      0.80      0.82      3697
  Наука и техника       0.84      0.85      0.84      1438
      Путешествия       0.67      0.81      0.73       173
           Россия       0.85      0.78      0.82      4342
Силовые структуры       0.62      0.67      0.65       530
            Спорт       0.97      0.96      0.96      1743
         Ценности       0.91      0.86      0.88       210
        Экономика       0.83      0.87      0.85      2152

         accuracy                           0.82     20000
        macro avg       0.67      0.64      0.64     20000
     weighted avg       0.82      0.82      0.82     20000